extension_types:
  '0': server_name
  '1': max_fragment_length
  '10': supported_groups
  '10794': grease
  10795-14905: Unassigned
  '11': ec_point_formats
  '12': srp
  '13': signature_algorithms
  '14': use_srtp
  '14906': grease
  14907-19017: Unassigned
  '15': heartbeat
  '16': application_layer_protocol_negotiation
  '17': status_request_v2
  '18': signed_certificate_timestamp
  '19': client_certificate_type
  '19018': grease
  19019-23129: Unassigned
  '2': client_certificate_url
  '20': server_certificate_type
  '21': padding
  '22': encrypt_then_mac
  '23': extended_master_secret
  '23130': grease
  23131-27241: Unassigned
  '24': token_binding
  '25': cached_info
  '2570': grease
  2571-6681: Unassigned
  '26': tls_lts
  '27': compress_certificate
  '27242': grease
  27243-31353: Unassigned
  '28': record_size_limit
  '29': pwd_protect
  '3': trusted_ca_keys
  '30': pwd_clear
  '31': password_salt
  '31354': grease
  31355-35465: Unassigned
  '32': ticket_pinning
  '33': tls_cert_with_extern_psk
  '34': delegated_credential
  '35': session_ticket
  '35466': grease
  35467-39577: Unassigned
  '36': TLMSP
  '37': TLMSP_proxying
  '38': TLMSP_delegate
  '39': supported_ekt_ciphers
  '39578': grease
  39579-43689: Unassigned
  '4': truncated_hmac
  '40': grease
  '41': pre_shared_key
  '42': early_data
  '43': supported_versions
  '43690': grease
  43691-47801: Unassigned
  '44': cookie
  '45': psk_key_exchange_modes
  '46': grease
  '47': certificate_authorities
  '47802': grease
  47803-51913: Unassigned
  '48': oid_filters
  '49': post_handshake_auth
  '5': status_request
  '50': signature_algorithms_cert
  '51': key_share
  '51914': grease
  51915-56025: Unassigned
  '52': transparency_info
  '53': connection_id
  '54': connection_id
  '55': external_id_hash
  '56': external_session_id
  '56026': grease
  56027-60137: Unassigned
  '57': quic_transport_parameters
  '58': ticket_request
  '59': dnssec_chain
  '6': user_mapping
  '60': sequence_number_encryption_algorithms
  '60138': grease
  60139-64249: Unassigned
  61-2569: Unassigned
  '64250': grease
  64251-65279: Unassigned
  '65280': Reserved for Private Use
  '65281': renegotiation_info
  65282-65535: Reserved for Private Use
  '6682': grease
  6683-10793: Unassigned
  '7': client_authz
  '8': server_authz
  '9': cert_type
handshake_types:
  '0': hello_request_RESERVED
  '1': client_hello
  '10': new_connection_id
  '11': certificate
  '12': server_key_exchange_RESERVED
  '13': certificate_request
  '14': server_hello_done_RESERVED
  '15': certificate_verify
  '16': client_key_exchange_RESERVED
  '17': client_certificate_request
  18-19: Unassigned
  '2': server_hello
  '20': finished
  '21': certificate_url_RESERVED
  '22': certificate_status_RESERVED
  '23': supplemental_data_RESERVED
  '24': key_update
  '25': compressed_certificate
  '254': message_hash
  '255': Unassigned
  '26': ekt_key
  27-253: Unassigned
  '3': hello_verify_request_RESERVED
  '4': new_session_ticket
  '5': end_of_early_data
  '6': hello_retry_request_RESERVED
  '7': Unassigned
  '8': encrypted_extensions
  '9': request_connection_id
